### ISSUE TITLE
Consider using bracket-lib for greater accessibility

### ISSUE THREAD

**Issue by erlend-sh** [Micutio/innit#1]
> A long-term goal, would be to create an educational experience as well.

Might you consider swapping out tcod for [bracket-lib](https://github.com/thebracket/bracket-lib)? tcod is great, but there's a pretty good case to be made for @thebracket's bracket-lib as a more education-friendly foundation:

- Pure Rust
- Easy web support
- [Extensive tutorial](https://bfnightly.bracketproductions.com/rustbook/)
- Upcoming ["Hands-on Rust"](https://pragprog.com/titles/hwrust/hands-on-rust/) book

Innit is one of the most mature Rust ascii games around, so it'd be a great showcase/example game for bracket-lib.

**Comment by Micutio** [comment]
Thanks for bringing bracket-lib to my attention. At a first glance it looks intriguing, especially considering the wealth of features, lack of non-Rust dependencies and the attention to building for the web.

As tcod is focused on peripherals, i.e.: graphics output and user input, bracket-lib would be primarily used to do the same. I've been building the core mechanics like component system and game-loop from scratch. Whether Innit makes the switch or not, these core mechanics will likely remain for the foreseeable future until the game grows to a point where more abstraction is necessary.

This suggestion also comes at a crucial point in time as I am looking to overhaul the game UI to fit the gameplay and include full mouse support. To avoid doing the same work twice I'll peruse the tutorial and code to see how much work for migrating the engine we're looking at here before commencing the UI overhaul. So you can expect a response soon.

> Innit is one of the most mature Rust ascii games around, so it'd be a great showcase/example game for bracket-lib.

Thank you, this is high praise. Given that Innit doesn't even have a playable alpha version out yet I'm unsure of its justification but I'll take it as encouragement to keep pouring quality work into it.

**Comment by Micutio** [comment]
Innit has now been migrated to bracket-lib, see https://github.com/Micutio/innit/pull/2#issue-534525676
